-- SQL script to set up database in Supabase SQL Editor

-- 1. Create weddings table
CREATE TABLE IF NOT EXISTS weddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT UNIQUE NOT NULL,
    secret_key TEXT NOT NULL,
    groom_name TEXT NOT NULL,
    bride_name TEXT NOT NULL,
    event_date TIMESTAMPTZ,
    location_info JSONB DEFAULT '{}'::jsonb,
    music_url TEXT,
    images TEXT[] DEFAULT '{}',
    template_id TEXT NOT NULL DEFAULT 'TemplateA',
    custom_domain TEXT UNIQUE, -- Cột lưu trữ tên miền riêng
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 2. Create wishes table
CREATE TABLE IF NOT EXISTS wishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wedding_id UUID NOT NULL REFERENCES weddings(id) ON DELETE CASCADE,
    guest_name TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- 3. Enable indexes for faster querying
CREATE INDEX IF NOT EXISTS idx_weddings_slug ON weddings(slug);
CREATE INDEX IF NOT EXISTS idx_weddings_custom_domain ON weddings(custom_domain);
CREATE INDEX IF NOT EXISTS idx_wishes_wedding_id ON wishes(wedding_id);

-- Note: In Supabase, make sure Row Level Security (RLS) is configured.
-- For a simple start, you can disable RLS for these tables or add public policies.
-- Public Policies (Optional but recommended):
-- weddings: allow anyone to select (read)
-- wishes: allow anyone to select (read) and insert (create wishes)
ALTER TABLE weddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE wishes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to weddings" ON weddings
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public read access to wishes" ON wishes
    FOR SELECT TO public USING (true);

CREATE POLICY "Allow public insert access to wishes" ON wishes
    FOR INSERT TO public WITH CHECK (true);

CREATE POLICY "Allow public delete access to wishes" ON wishes
    FOR DELETE TO public USING (true);

-- 4. Insert demo wedding for Minh Hoàng & Mai Hương
INSERT INTO weddings (
    slug, 
    secret_key, 
    groom_name, 
    bride_name, 
    event_date, 
    location_info, 
    template_id,
    custom_domain
) VALUES (
    'minhhoang-maihuong',
    'key123',
    'Minh Hoàng',
    'Mai Hương',
    '2026-10-10T11:00:00+07:00',
    '{
        "groom_family": {
            "father_name": "Nguyễn Văn A",
            "mother_name": "Lê Thị B",
            "address": "123 Đường Láng, Đống Đa, Hà Nội",
            "time": "11:00",
            "date": "10/10/2026",
            "map_url": "https://maps.google.com"
        },
        "bride_family": {
            "father_name": "Trần Văn C",
            "mother_name": "Phạm Thị D",
            "address": "456 Nguyễn Huệ, Quận 1, TP. HCM",
            "time": "11:00",
            "date": "10/10/2026",
            "map_url": "https://maps.google.com"
        }
    }'::jsonb,
    'TemplateA',
    'wedding-nhathm.com'
) ON CONFLICT (slug) DO NOTHING;
